### ISSUE TITLE
Support for kubernetes v1.27.1

### ISSUE THREAD

**Issue by Nox-404** [qnap-dev/QNAP-CSI-PlugIn#2]
Hello,
I tried installing the plugin on a kubernetes v1.27.1 cluster.
But it seems that it requires PodSecurityPolicies which have been deprecated in 1.21 and removed in 1.25.

I patched the chart to not create the PSP in a fork of this repository but the operator itself is looking for it and thus fails to start.

Is there plans to support more recent clusters ?

**Comment by JimmyTanMPM** [comment]
Hi Sir,
Thanks for your suggestions.
QNAP is scheduled support v1.27.1 into official release version.

Once official release we will announce by E-news, thanks

**Comment by gizmotronic** [comment]
This is true for Kubernetes 1.25 and later, and so it's not possible to use this CSI provider for any currently supported version of Kubernetes.

**Comment by JimmyTanMPM** [comment]
Hi @gizmotronic 
QNAP CSI driver support 1.21 to 1.27 Kubernetes version in v1.1.0, for your reference

**Comment by kristvanbesien** [comment]
Will this also duspport 1.28? Have been trying to get this to work, but without success so far.

**Comment by LeonaChen2727** [comment]
I'm pleased to announce that the newest QNAP CSI plugin has been released!
It supports Kubernetes versions from 1.24 to 1.30.

For more information, please refer to the release notes: 
https://github.com/qnap-dev/QNAP-CSI-PlugIn/releases/tag/v1.3.0
