### ISSUE TITLE
Support for newer version of k8s

### ISSUE THREAD

**Issue by darioneto** [qnap-dev/QNAP-CSI-PlugIn#3]
I'm unable to run this on 1.25 due to the security policies deprecation. Any chance this can be updated to support a newer version of k8s?

**Comment by JimmyTanMPM** [comment]
Hi Sir,
Thanks for your suggestions.
QNAP is scheduled support v1.27.1 into official release version.

Once official release we will announce by E-news, thanks

**Comment by darioneto** [comment]
Thanks for your reply, Do we know the approx ETA for this release yet?

**Comment by JimmyTanMPM** [comment]
Hi @darioneto 
hope you are doing fine.
v1.1.0 version is released contain v1.27.1.

**Comment by LeonaChen2727** [comment]
Hi, 
We already have plans for an upgraded version, please stay tuned.

**Comment by LeonaChen2727** [comment]
Hi, 
I'm pleased to announce that the newest QNAP CSI plugin has been released!
It supports Kubernetes versions from 1.24 to 1.30.

For more information, please refer to the release notes: 
https://github.com/qnap-dev/QNAP-CSI-PlugIn/releases/tag/v1.3.0
