### ISSUE TITLE
Feature Request: Ability to create a BackendConfiguration without tridentctl 

### ISSUE THREAD

**Issue by heckelmann** [qnap-dev/QNAP-CSI-PlugIn#5]
Currently, it is impossible to create a BackendConfig without using the tridentctl CLI.

```
./bin/tridentctl create backend -f <backend.json> -n trident 
```

To entirely automate the Setup of the CSI and to be able to use it in a GitOps-based setup (like with ArgoCD, Flagger etc.), it would be needed to have the same option to create a `TridentBackendConfig` Custom Resource as described here https://docs.netapp.com/us-en/trident/trident-use/backend-kubectl.html#step-2-create-the-tridentbackendconfig-cr.

Maybe this is already possible, but it is missing the Documentation on how to do so.

**Comment by jmrr** [comment]
Hi @heckelmann did you get any further on this? We're blocked by #4 but would want to create the CRDs with ArgoCD too so interested in knowing if you've had any success with this. Thanks!

**Comment by heckelmann** [comment]
> Hi @heckelmann did you get any further on this? We're blocked by #4 but would want to create the CRDs with ArgoCD too so interested in knowing if you've had any success with this. Thanks!

Unfortunately, not...

**Comment by JimmyTanMPM** [comment]
Hi @heckelmann 

This feature is under evaluation, if there is more information to share for pushing this case into development stages, please let me know.

**Comment by jmrr** [comment]
Yes, so the idea is that instead of using the `tridentctl` CLI to create the `*.trident.qnap.io` CRDs that support the `qnap-csi` plugin, we would be able to understand how to configure the manifests for the CRDs so we can use `gitops` to deploy them, similar to how  we deploy the `trident` Operator. It can be just sharing the manifests through a `kustomization` or a `helm` chart.

**Comment by JimmyTanMPM** [comment]
Hi @jmrr @heckelmann 
v1.2.0 is released
Please refer to release notes
(https://github.com/qnap-dev/QNAP-CSI-PlugIn/releases/tag/v1.2.0)

**Comment by heckelmann** [comment]
Thank you @JimmyTanMPM!

I'll give it a try - Thank you!
