### ISSUE TITLE
ARM64 and ARMv7 support

### ISSUE THREAD

**Issue by l0ner** [qnap-dev/QNAP-CSI-PlugIn#6]
Hi

I see that the images for qnap-csi-operator and qnap-csi are currently available only for amd64 architecture (despite the fact that in bundle.yml node selector allows for arm64 nodes).

this means that the trident-operator cannot start on arm64 arch, and instead fails with 'exec /trident-operator: exec format error' error.

Having arm64 and armv7 images would be really nice for small lab clusters made of arm machines (like raspberry pi's).

Do you have any plans for supporting arm architectures?

**Comment by JimmyTanMPM** [comment]
Hi @l0ner 

QNAP will keep evaluate ARM64 and ARMv7 usage in marketing 
Could you share more scenario for using ARM64 and ARMv7, if that is possible. 
That will help QNAP pushing this case to development.

**Comment by garand43** [comment]
This would be an excellent addition.  I recently setup a small Rapsberry Pi 4b k8s cluster for learning more about containers and helm charts.  I would like to use my QNAP via a CSI driver for persistent pod storage.  While this could probably be done via an NFS share and the appropriate storage class, using the CSI is more desirable.

Thanks.

**Comment by JimmyTanMPM** [comment]
Hi @garand43 
v1.2.0 is released
Please refer to release notes
(https://github.com/qnap-dev/QNAP-CSI-PlugIn/releases/tag/v1.2.0)

**Comment by garand43** [comment]
Hi @JimmyTanMPM 

Finally got volumes working from k8s running on Raspberry Pi 4Bs to my QNAP using iSCSI.  The config instructions in the readme.md are a little off.  trident-csi is a service and not a deployment.  The valid deployments are trident-controller and trident-operator.  The backend configuration is a little confusing as well, although I haven't looked at the upstream trident docs.

Thanks for getting this added to your CSI.

- garand43
