### ISSUE TITLE
TS-531X and kubernetes 1.30.x support

### ISSUE THREAD

**Issue by Hr46ph** [qnap-dev/QNAP-CSI-PlugIn#9]
Hey all,

I tried the CSI plugin yesterday and creating the backend with the json failed with:
`Error: could not create backend: problem initializing storage driver 'qnap-iscsi': rpc error: code = Unknown desc = QTS Pool LIST Failed : List Pool Fail, API Result Return :  (400 Bad Request)`

I wonder why this is, is the 531X perhaps not supported or could it be due to Kubernetes version 1.30.?

Thanks!

**Comment by Hr46ph** [comment]
Thanks for the answer.

Unfortunately downgrading is not an option.

Do you have a timeline for supporting newer versions of Kubernetes?

**Comment by LeonaChen2727** [comment]
We have arranged the development to support Kubernetes version 1.30.

**Comment by louhisuo** [comment]
Kubernetes upstream release 1.31 is already released. When you plan to support Kubernetes 1.30 for QNAP CSI Driver?

**Comment by LeonaChen2727** [comment]
We are pleased to inform you that QNAP CSI Plugin v1.3.0 has been released today. This new version now supports Kubernetes versions ranging from 1.24 to 1.30.

Thank you for your continued support.
